---
title: "ADA_Midterm"
author: "Caitlin O'Connell"
date: '2022-10-13'
output: html_document
---

## Load packages and open libraries 
```{r, echo=TRUE, message = F}
pacman::p_load(dplyr, readr, ggplot2) 

```

## a) Import titanic dataset located at "https://github.com/kijohnson/Data" calling the dataframe titanic
```{r}
titanic <- read_csv("https://raw.githubusercontent.com/kijohnson/Data/main/titanic.csv")
```

## b) determining the median age for by passenger class
```{r}
# determining how many passenger classes are in the dataset
table(titanic$Pclass, useNA = "always")

# looking at Age values to ensure all look reasonable
table(titanic$Age, useNA = "always")

# calculating median age
by(titanic$Age, titanic$Pclass, median)

```

## c) Create a plot that shows medians, spread of data, and outliers for the continuous variable age according to passenger class
```{r}
  ggplot(data = titanic, aes(x = as.factor(Pclass), y = Age)) +
  geom_boxplot(aes(fill = as.factor(Pclass))) +
  labs(x = "Passenger Class", y = "Age in years", title = "Boxplot of Age by Passenger Class") + 
  theme(legend.position = "null"
       )
```

## Saving plot
```{r}
# Defaults to last plot displayed.
ggsave(filename = "midtermQ3plot.png",
       width = 4, height = 4, units = "in", bg="white") 
```


## Calculating percentage of males and females per passenger class
```{r}
# first checking summary of variable sex
table(titanic$Sex, useNA = "always")

# calculating percentage of males and females per passenger class
sex_by_pclass <- titanic %>%
  group_by(Pclass, Sex) %>%
  count() %>% 
  group_by(Pclass) %>% 
  mutate(percentage = 100*n/sum(n))

# printing dataframe
sex_by_pclass

```
